### ISSUE TITLE
Fable works, Npm doesn't

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [drk-mtr/FableReactNative#1]
```
D:\projects\FableReactNative\ExpoCode>npm start

> start
> expo start

'expo' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code 1
npm ERR! path D:\projects\FableReactNative\ExpoCode
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c expo start

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bdimp\AppData\Local\npm-cache\_logs\2021-03-08T22_38_03_452Z-debug.log
```

log file:
[2021-03-08T22_38_03_452Z-debug.log](https://github.com/drk-mtr/FableReactNative/files/6104590/2021-03-08T22_38_03_452Z-debug.log)

**Comment by ImaginaryDevelopment** [comment]
it seems `yarn` followed by `yarn add expo-cli` then `yarn run android` have me to the project starting up, the emulator starting up and running! I'd like to know if you have any clues on why the instructions for npm didn't work for me?

**Comment by drk-mtr** [comment]
Glad you got it working, that was just me going with habit when writing the readme notes in a hurry - I've updated the readme just in case anyone else stumbles across this. 

Makes sense to use yarn for React stuff generally in my view, for obvious reasons :)
